# Generated by Django 3.2.7 on 2021-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote_dash_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_author',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
